name: Generate Documentation
on: [push]

jobs:
  deploy:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        # required for fdint
        # pip install numpy
        # pip install -r requirements.txt
        pip install jupyter jupyter_contrib_nbextensions
    - name: Build
      id: build
      shell: bash
      run: |
        python setup.py build_doc
    - name: Upload Documentation
      id: upload-docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
